d0=graph(group0vars,ofinterestnames,'omitselfloops');
h0=graph(group0high,ofinterestnames,'omitselfloops');
p0=plot(d0,'Layout','force','UseGravity','on')
highlight(p0,h0,'EdgeColor','r')
cla;
d1=graph(group1vars,ofinterestnames,'omitselfloops');
h1=graph(group1high,ofinterestnames,'omitselfloops');
p1=plot(d1,'Layout','force','UseGravity','on')
highlight(p1,h1,'EdgeColor','r')
cla;
d2=graph(group2vars,ofinterestnames,'omitselfloops');
h2=graph(group2high,ofinterestnames,'omitselfloops');
p2=plot(d2,'Layout','force','UseGravity','on')
highlight(p2,h2,'EdgeColor','r')
cla;
d3=graph(group3vars,ofinterestnames,'omitselfloops');
h3=graph(group3high,ofinterestnames,'omitselfloops');
p3=plot(d3,'Layout','force','UseGravity','on')
highlight(p3,h3,'EdgeColor','r')
cla;

