group0comp=zeros(1215,1215);
group1comp=zeros(1215,1215);
group2comp=zeros(1215,1215);
group3comp=zeros(1215,1215);
for n=0:98
    %% Import the data
    [~, ~, raw] = xlsread(strcat('/Users/marianneaguilar/Documents/4exampleidentityiteration',num2str(n),'.xlsx'),'Sheet1');
    raw = raw(2:end,2:end);
    %% Create output variable
    exampleidentity = reshape([raw{:}],size(raw));
    %% Clear temporary variables
    clearvars raw;
    [~, ~, raw] = xlsread(strcat('/Users/marianneaguilar/Documents/4example2identityiteration',num2str(n),'.xlsx'),'Sheet2');
    raw = raw(2:end,2:end);
    example2identity = reshape([raw{:}],size(raw));
    clearvars raw;
    [~, ~, raw] = xlsread(strcat('/Users/marianneaguilar/Documents/4example3identityiteration',num2str(n),'.xlsx'),'Sheet3');
    raw = raw(2:end,2:end);
    example3identity = reshape([raw{:}],size(raw));
    clearvars raw;
    [~, ~, raw] = xlsread(strcat('/Users/marianneaguilar/Documents/4example4identityiteration',num2str(n),'.xlsx'),'Sheet4');
    raw = raw(2:end,2:end);
    example4identity = reshape([raw{:}],size(raw));
    clearvars raw;
    for i=0:1214
        for j=0:1214
            comp1=mod(i,27);
            comp2=mod(j,27);
            if comp1<=comp2
                v1=exampleidentity(i+1,:);
                v2=exampleidentity(j+1,:);
                v1abs=abs(v1);
                v2abs=abs(v2);
                v3=example2identity(i+1,:);
                v4=example2identity(j+1,:);
                v3abs=abs(v3);
                v4abs=abs(v4);
                v5=example3identity(i+1,:);
                v6=example3identity(j+1,:);
                v5abs=abs(v5);
                v6abs=abs(v6);
                v7=example4identity(i+1,:);
                v8=example4identity(j+1,:);
                v7abs=abs(v7);
                v8abs=abs(v8);
                group0comp(i+1,j+1)=group0comp(i+1,j+1)+dot(v1,v2)/dot(v1abs,v2abs);
                group1comp(i+1,j+1)=group1comp(i+1,j+1)+dot(v3,v4)/dot(v3abs,v4abs);
                group2comp(i+1,j+1)=group2comp(i+1,j+1)+dot(v5,v6)/dot(v5abs,v6abs);
                group3comp(i+1,j+1)=group3comp(i+1,j+1)+dot(v7,v8)/dot(v7abs,v8abs);
            end
        end
    end
end
group0comp=group0comp/100;
group1comp=group1comp/100;
group2comp=group2comp/100;
group3comp=group3comp/100;

group0vars=zeros(45,45);
group1vars=zeros(45,45);
group2vars=zeros(45,45);
group3vars=zeros(45,45);
group0high=zeros(45,45);
group1high=zeros(45,45);
group2high=zeros(45,45);
group3high=zeros(45,45);
for i=0:44
    for j=0:44
        begin=i*27+1;
        ed=(i+1)*27;
        begin2=j*27+1;
        ed2=(j+1)*27;
        det0=det(group0comp(begin:ed,begin2:ed2));
        det1=det(group1comp(begin:ed,begin2:ed2));
        det2=det(group2comp(begin:ed,begin2:ed2));
        det3=det(group3comp(begin:ed,begin2:ed2));
        group0vars(i+1,j+1)=det0;
        if det0<0
            group0high(i+1,j+1)=det0;
        end
        group1vars(i+1,j+1)=det1;
        if det1<0
            group1high(i+1,j+1)=det1;
        end
        group2vars(i+1,j+1)=det2;
        if det2<0
            group2high(i+1,j+1)=det2;
        end
        group3vars(i+1,j+1)=det3;
        if det3<0
            group3high(i+1,j+1)=det3;
        end
    end
end

temp0=reshape(group0vars,[2025,1]);
temp1=reshape(group1vars,[2025,1]);
temp2=reshape(group2vars,[2025,1]);
temp3=reshape(group3vars,[2025,1]);
top0=min(maxk(temp0,245));
top1=min(maxk(temp1,245));
top2=min(maxk(temp2,245));
top3=min(maxk(temp3,245));
bot0=max(mink(temp0,200));
bot1=max(mink(temp1,200));
bot2=max(mink(temp2,200));
bot3=max(mink(temp3,200));
for i=1:45
    for j=1:45
        if group0vars(i,j)<top0 & group0vars(i,j)>bot0
            group0vars(i,j)=0;
            group0high(i,j)=0;
        end
        if group1vars(i,j)<top1 & group1vars(i,j)>bot1
            group1vars(i,j)=0;
            group1high(i,j)=0;
        end
        if group2vars(i,j)<top2 & group2vars(i,j)>bot2
            group2vars(i,j)=0;
            group2high(i,j)=0;
        end
        if group3vars(i,j)<top3 & group3vars(i,j)>bot3
            group3vars(i,j)=0;
            group3high(i,j)=0;
        end
    end
end

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/marianneaguilar/Documents/ofinterestnames.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/06 19:47:01

%% Import the data
[~, ~, ofinterestnames] = xlsread('/Users/marianneaguilar/Documents/ofinterestnames.xlsx','Sheet1');
ofinterestnames = ofinterestnames(2:end,end);
ofinterestnames(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),ofinterestnames)) = {''};
for i=1:length(ofinterestnames)
    ofinterestnames(i)=strrep(ofinterestnames(i),'_',' ');
end

